### ISSUE TITLE
iNEXT function

### ISSUE THREAD

**Issue by mmcardozo** [chassenr/NGS#2]
Hi,

I'm trying to use the function iNEXTplot to obtain a rarefaction plot from the output of iNEXT(), but so far not successful. I have 25 samples and I ran iNEXT as:

library(iNEXT)
OTU=read.table("OTU_names_PeakPOC.txt", h=T) 
Bact <- iNEXT(OTU, q=c(0, 1, 2), datatype="abundance", endpoint=NULL, se=TRUE, conf=0.95, nboot=100) 
save.image("OTU_names_PeakPOC.Rdata")
quit()

And then the function:

iNEXTplot <- function(
  Bact,
  hill = c(0, 1, 2),
  color = rainbow(length(Bact$iNextEst)),
  labels = names(Bact$iNextEst),
  selection = 1:length(Bact$iNextEst),
  window.new = T,
  ylim = c(0, max(as.matrix(Bact2$qD.UCL))),
  dynamic.ylim = F,
  xlim = c(0, max(as.matrix(Bact2$m)))
) {
  
  # format input
  Bact1 <- vector("list", length = 6)
  names(Bact1) <- c("m", "method", "order", "qD", "qD.LCL", "qD.UCL")
  # create subset for hill number estimates
  Bact1$qD <- sapply(Bact$iNextEst, function(x) { x$qD })
  # create subset for upper CI
  Bact1$qD.UCL <- sapply(Bact$iNextEst, function(x) { x$qD.UCL })
  # create subset for lower CI
  Bact1$qD.LCL <- sapply(Bact$iNextEst, function(x) { x$qD.LCL })
  # create subset for sequencing depth
  Bact1$m <- sapply(Bact$iNextEst, function(x) { x$m })
  # create subset for sequencing depth
  Bact1$method <- sapply(Bact$iNextEst, function(x) { x$method })
  # create subset for order of hill numbers
  Bact1$order <- sapply(Bact$iNextEst, function(x) { x$order })
  
  # apply selection
  Bact2 <- lapply(Bact1, function(x) { x[, selection] })
  color2 <- color[selection]
  labels2 <- labels[selection]
  
  # open new graphics device
  if (window.new == T) {
    windows(width = (length(hill) + 1) * 5, height = 10)
  }
  par(mfrow = c(1, length(hill) + 1))
  
  for (i in 1:length(hill)) {
    # adjust ylim
    if(dynamic.ylim == T) {
      ylim <- c(0, max(as.matrix(Bact2$qD.UCL[Bact2$order[, 1] == hill[i], ]))) 
    } 
    
    # create empty plot
    plot(
      0, 0,
      type = "n",
      xlim = xlim,
      ylim = ylim,
      xlab = "Number of sequences",
      ylab = paste("q = ", hill[i], sep = ""),
      axes = F
    )
    
    # add axes
    axis(1, cex.axis = 0.8)
    axis(2, cex.axis = 0.8, las = 2)
    
    # subset data to hill number of interest
    Bact.sub <- lapply(Bact2, function(x) { x[Bact2$order[, 1] == hill[i], ] })
    
    # add data
    for (j in 1:ncol(Bact.sub$qD)) {
      polygon(
        x = c(Bact.sub$m[, j], rev(Bact.sub$m[, j])),
        y = c(Bact.sub$qD.UCL[, j], rev(Bact.sub$qD.LCL[, j])),
        col = adjustcolor(color2[j], alpha.f = 0.3),
        border = NA
      )
      lines(
        Bact.sub$m[Bact.sub$method[, j] != "extrapolated", j],
        Bact.sub$qD[Bact.sub$method[, j] != "extrapolated", j],
        col = color2[j],
        lty = 1
      )
      lines(
        Bact.sub$m[Bact.sub$method[, j] == "extrapolated", j],
        Bact.sub$qD[Bact.sub$method[, j] == "extrapolated", j],
        col = color2[j],
        lty = 3
      )
    }
  }
  
  # add legend
  plot(
    0, 0,
    type = "n",
    axes = F,
    xlim = c(0, 5),
    ylim = c(1, ncol(Bact.sub$qD)),
    xlab = "",
    ylab = ""
  )
  points(
    x = rep(0.5, ncol(Bact.sub$qD)),
    y = 1:ncol(Bact.sub$qD),
    cex = 2,
    pch = 15,
    col = adjustcolor(color2, alpha.f = 0.3)
  )
  segments(
    x0 = rep(0, ncol(Bact.sub$qD)),
    y0 = 1:ncol(Bact.sub$qD),
    x1 = rep(1, ncol(Bact.sub$qD)),
    y1 = 1:ncol(Bact.sub$qD),
    lty = 1,
    col = color2
  )
  text(
    x = rep(1, ncol(Bact.sub$qD)),
    y = 1:ncol(Bact.sub$qD),
    pos = 4,
    labels = labels2,
    cex = 0.8
  )
}

How do you suggest to run this function?

Many thanks!

**Comment by chassenr** [comment]
@mmcardozo It look to me that you are loading the plotting function into your workspace. You could also have used ```source("iNEXTplot.R")```. After you load the function, you still have to actually run it, i.e. supply your user-specific values for each argument in the function that deviate from the default (just like any other R command):
```
iNEXTplot(
Bact,
hill = c(0, 2),
window.new = F
)
```
If you are a fan of ggplot2, you can also use the plotting function that comes with the iNEXT package. I only wrote this plotting function, because I wanted a non-ggplot2 alternative.

**Comment by mmcardozo** [comment]
Update:

I think is a problem of my dataset. I tried: 

source(“~/iNEXTplot.R”)

myplot <- iNEXTplot(Bact, hill = c(0 ,2), window.new = F) 

It produced a value myplot NULL(empty)

And also ggiNEXT:

library(iNEXT)
library(ggplot2)

pdf(“iNEXT.pdf”)
ggiNEXT(Bact, type=1, facet.var=“site”, grey=TRUE)


Produces a pdf 0 bytes that cannot be opened.

Both didn’t work. I’m going to look into my dataset.


Am 05.04.2019 um 11:55 schrieb Christiane Hassenrück <notifications@github.com <mailto:notifications@github.com> >:

@mmcardozo It look to me that you are loading the plotting function into your workspace. You could also have used source("iNEXTplot.R"). After you load the function, you still have to actually run it, i.e. supply your user-specific values for each argument in the function that deviate from the default (just like any other R command):


iNEXTplot(
Bact,
hill = c(0, 2),
window.new = F
)


If you are a fan of ggplot2, you can also use the plotting function that comes with the iNEXT package. I only wrote this plotting function, because I wanted a non-ggplot2 alternative.

**Comment by chassenr** [comment]
@mmcardozo I wrote that function quite some time ago. It is possible that the iNEXT function was updated and that now the iNEXT object doesn't work with my plotting function anymore. However, it is weird that also the ggplot2 command won't work. Let me know if you find anything. 
I am also a little bit confused why you are assigning the output of the plotting function to an R object. The plotting function is not intended to return any output, apart from displaying the graph.

**Comment by mmcardozo** [comment]
I don’t apply functions that often. I normally do to later save the graph. I’ll update you as soon as I find something. 

Am 05.04.2019 um 17:21 schrieb Christiane Hassenrück <notifications@github.com <mailto:notifications@github.com> >:

@mmcardozo I wrote that function quite some time ago. It is possible that the iNEXT function was updated and that now the iNEXT object doesn't work with my plotting function anymore. However, it is weird that also the ggplot2 command won't work. Let me know if you find anything.
I am also a little bit confused why you are assigning the output of the plotting function to an R object. The plotting function is not intended to return any output, apart from displaying the graph.

**Comment by mmcardozo** [comment]
Hi again,



The output of the iNEXT is fine, this worked on the server:



R
load("iNEXT_PeakPOC.Rdata")
source("iNEXTplot.R")
iNEXTplot(Bact, hill = c(0, 1, 2), window.new = F)
q() # creates a Rplots.pdf file in the working directory



but this won't work on the rstudio in my local computer:



setwd("~/PhD/Projects/Seasonality/Sediment_traps/Output_MC_traps_and_PeakPOC/Rwork/iNEXT/") 
load("iNEXT_PeakPOC.Rdata")
source("iNEXTplot.R")
quartz()
pdf("Rplot.pdf")
iNEXTplot(Bact, hill = c(0, 1, 2), window.new = F) #still creates a pdf that cannot be opened



sounds like is a problem related with the creation of the pdf, since I'm working on a mac, it occurs even if I silence the quartz option. Might work on a windows computer, but I'll dig deeper into that 



-----Original message-----

**Comment by chassenr** [comment]
@mmcardozo On the server, if no X11 forwarding is enabled, R will automatically generate pdf for plots. On your local mac, Rstudio will generate plots in the plotting panel if you don't open a separate device. The separate plotting device should be either quartz or pdf (but not both). Same as on the server, to view the pdf you will have to close the plotting device using ```dev.off()```

**Comment by mmcardozo** [comment]
yes it worked! 

Thank you for your time



-----Original message-----
